// ui/src/TodoItem.tsx
import * as React from "react";
import classNames from "classnames";

interface TodoItemProps {
    completed: boolean,
    text: string
}

// Create a TodoMVC template
// Rule the web

class TodoItem extends React.Component<TodoItemProps> {

    handleToggle = () => {

    };

    handleChange = () => {

    };

    render() {
        const {completed, text} = this.props;
        return (
            <li className={classNames({completed})}>
                <div className="view">
                    <input className="toggle" type="checkbox" onChange={this.handleToggle} checked={completed}/>
                    <label>{text}</label>
                    <button className="destroy"></button>
                </div>
                <input className="edit" value="Create a TodoMVC template" onChange={this.handleChange}/>
            </li>
        );
    }
}

export default TodoItem;

// ui/vite-vue/src/components/TodoItem.vue
<!--
<template>
  <li class="completed">
    <div class="view">
      <input checked class="toggle" type="checkbox">
      <label>Taste JavaScript</label>
      <button class="destroy"></button>
    </div>
    <input class="edit" value="Create a TodoMVC template">
  </li>
</template>
-->
<script lang="ts" setup>
// defineProps()
</script>

<template>
  <li>
    <div class="view">
      <input class="toggle" type="checkbox">
      <label>Buy a unicorn</label>
      <button class="destroy" />
    </div>
    <input class="edit" value="Rule the web">
  </li>
</template>
